import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "normalize.css";
import "./pico.classless.min.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul>
              <li>
                <strong>{"Nhập môn lập trình Python"}</strong>
              </li>
            </ul>
            <ul>
              <li>
                <a href="/t">{"Danh sách câu hỏi"}</a>
              </li>
              <li>
                <a href="/q">{"Đặt câu hỏi"}</a>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
